// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type User struct {
	ID       string         `json:"id"`
	Password string         `json:"password"`
	Email    string         `json:"email"`
	Created  sql.NullTime   `json:"created"`
	Fullname sql.NullString `json:"fullname"`
}
