// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"time"

	"github.com/jackc/pgtype"
	null "gopkg.in/guregu/null.v4"
)

type Notification struct {
	ID                  string      `json:"id"`
	RedisID             null.String `json:"redisID"`
	NotificationGroupID string      `json:"notificationGroupID"`
	Created             null.Time   `json:"created"`
	Read                null.Time   `json:"read"`
	CurrentMainStep     null.Int    `json:"currentMainStep"`
	CurrentSubStep      null.Int    `json:"currentSubStep"`
	MainMessage         null.String `json:"mainMessage"`
	SubMessage          null.String `json:"subMessage"`
}

type NotificationsGroup struct {
	ID             string      `json:"id"`
	UserID         string      `json:"userID"`
	WorkflowID     null.String `json:"workflowID"`
	EntityID       string      `json:"entityID"`
	EntityType     string      `json:"entityType"`
	TotalMainSteps null.Int    `json:"totalMainSteps"`
	TotalSubSteps  null.Int    `json:"totalSubSteps"`
}

type PlatformLazada struct {
	ID               string    `json:"id"`
	ShopID           string    `json:"shopID"`
	AccessToken      string    `json:"accessToken"`
	Country          string    `json:"country"`
	RefreshToken     string    `json:"refreshToken"`
	AccountPlatform  string    `json:"accountPlatform"`
	Account          string    `json:"account"`
	UserIDVn         string    `json:"userIDVn"`
	SellerIDVn       string    `json:"sellerIDVn"`
	ShortCodeVn      string    `json:"shortCodeVn"`
	RefreshExpiresIn null.Time `json:"refreshExpiresIn"`
	AccessExpiresIn  null.Time `json:"accessExpiresIn"`
	Created          null.Time `json:"created"`
}

type Product struct {
	ID           string         `json:"id"`
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	Msku         null.String    `json:"msku"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       string         `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Created      null.Time      `json:"created"`
	Updated      null.Time      `json:"updated"`
}

type ProductsAttributeLazada struct {
	ID                   string      `json:"id"`
	Name                 null.String `json:"name"`
	ShortDescription     null.String `json:"shortDescription"`
	Description          null.String `json:"description"`
	Brand                null.String `json:"brand"`
	Model                null.String `json:"model"`
	HeadphoneFeatures    null.String `json:"headphoneFeatures"`
	Bluetooth            null.String `json:"bluetooth"`
	WarrantyType         null.String `json:"warrantyType"`
	Warranty             null.String `json:"warranty"`
	Hazmat               null.String `json:"hazmat"`
	ExpireDate           null.String `json:"expireDate"`
	BrandClassification  null.String `json:"brandClassification"`
	IngredientPreference null.String `json:"ingredientPreference"`
	LotNumber            null.String `json:"lotNumber"`
	UnitsHb              null.String `json:"unitsHb"`
	FmltSkincare         null.String `json:"fmltSkincare"`
	Quantitative         null.String `json:"quantitative"`
	SkincareByAge        null.String `json:"skincareByAge"`
	SkinBenefit          null.String `json:"skinBenefit"`
	SkinType             null.String `json:"skinType"`
	UserManual           null.String `json:"userManual"`
	CountryOriginHb      null.String `json:"countryOriginHb"`
	ColorFamily          null.String `json:"colorFamily"`
	FragranceFamily      null.String `json:"fragranceFamily"`
	Source               null.String `json:"source"`
	ProductID            string      `json:"productID"`
}

type ProductsLazada struct {
	ID                    string      `json:"id"`
	LazadaID              int64       `json:"lazadaID"`
	LazadaPrimaryCategory int64       `json:"lazadaPrimaryCategory"`
	Created               time.Time   `json:"created"`
	Updated               time.Time   `json:"updated"`
	Status                null.String `json:"status"`
	SubStatus             null.String `json:"subStatus"`
	ShopID                string      `json:"shopID"`
}

type ProductsMedium struct {
	ID               string      `json:"id"`
	ProductID        string      `json:"productID"`
	OriginalFilename null.String `json:"originalFilename"`
	MurmurHash       null.Int    `json:"murmurHash"`
}

type ProductsPlatform struct {
	ProductID        string      `json:"productID"`
	ProductsLazadaID null.String `json:"productsLazadaID"`
}

type ProductsSkuLazada struct {
	ID              string      `json:"id"`
	Status          null.String `json:"status"`
	Quantity        null.Int    `json:"quantity"`
	SellerSku       string      `json:"sellerSku"`
	ShopSku         string      `json:"shopSku"`
	SkuID           null.Int    `json:"skuID"`
	Url             null.String `json:"url"`
	ColorFamily     null.String `json:"colorFamily"`
	Price           null.Int    `json:"price"`
	Available       null.Int    `json:"available"`
	PackageContent  null.String `json:"packageContent"`
	PackageWidth    null.String `json:"packageWidth"`
	PackageWeight   null.String `json:"packageWeight"`
	PackageLength   null.String `json:"packageLength"`
	PackageHeight   null.String `json:"packageHeight"`
	SpecialPrice    null.String `json:"specialPrice"`
	SpecialToTime   null.Time   `json:"specialToTime"`
	SpecialFromTime null.Time   `json:"specialFromTime"`
	SpecialFromDate null.Time   `json:"specialFromDate"`
	SpecialToDate   null.Time   `json:"specialToDate"`
	ProductID       string      `json:"productID"`
	ShopID          string      `json:"shopID"`
}

type Shop struct {
	ID         string    `json:"id"`
	UserID     string    `json:"userID"`
	ShopName   string    `json:"shopName"`
	Created    null.Time `json:"created"`
	LastUpdate null.Time `json:"lastUpdate"`
}

type ShopsPlatform struct {
	ID           string    `json:"id"`
	ShopID       string    `json:"shopID"`
	PlatformName string    `json:"platformName"`
	Created      null.Time `json:"created"`
}

type User struct {
	ID       string    `json:"id"`
	Password string    `json:"password"`
	Email    string    `json:"email"`
	Created  null.Time `json:"created"`
	Fullname string    `json:"fullname"`
}
