// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgtype"
	null "gopkg.in/guregu/null.v4"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, description, msku, selling_price, cost_price, shop_id,
  media_id, updated
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8
)
RETURNING id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated
`

type CreateProductParams struct {
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	Msku         null.String    `json:"msku"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       string         `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Updated      null.Time      `json:"updated"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Msku,
		arg.SellingPrice,
		arg.CostPrice,
		arg.ShopID,
		arg.MediaID,
		arg.Updated,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createProductMedia = `-- name: CreateProductMedia :one
INSERT INTO products_media (
  product_id, original_filename,
  murmur_hash, extension
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, product_id, original_filename, extension, murmur_hash
`

type CreateProductMediaParams struct {
	ProductID        string      `json:"productID"`
	OriginalFilename null.String `json:"originalFilename"`
	MurmurHash       null.Int    `json:"murmurHash"`
	Extension        null.String `json:"extension"`
}

func (q *Queries) CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, createProductMedia,
		arg.ProductID,
		arg.OriginalFilename,
		arg.MurmurHash,
		arg.Extension,
	)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const createProductPlatform = `-- name: CreateProductPlatform :one
INSERT INTO products_platform (
  product_id, products_lazada_id
) VALUES (
  $1, $2
)
RETURNING product_id, products_lazada_id
`

type CreateProductPlatformParams struct {
	ProductID        string      `json:"productID"`
	ProductsLazadaID null.String `json:"productsLazadaID"`
}

func (q *Queries) CreateProductPlatform(ctx context.Context, arg CreateProductPlatformParams) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, createProductPlatform, arg.ProductID, arg.ProductsLazadaID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductByProductMSKU = `-- name: GetProductByProductMSKU :one
SELECT id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated FROM products
WHERE msku = $1 AND shop_id = $2
LIMIT 1
`

type GetProductByProductMSKUParams struct {
	Msku   null.String `json:"msku"`
	ShopID string      `json:"shopID"`
}

func (q *Queries) GetProductByProductMSKU(ctx context.Context, arg GetProductByProductMSKUParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByProductMSKU, arg.Msku, arg.ShopID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductMediaByID = `-- name: GetProductMediaByID :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductMediaByID(ctx context.Context, id string) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByID, id)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductMediaByMurmur = `-- name: GetProductMediaByMurmur :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE murmur_hash = $1 AND product_id = $2
LIMIT 1
`

type GetProductMediaByMurmurParams struct {
	MurmurHash null.Int `json:"murmurHash"`
	ProductID  string   `json:"productID"`
}

func (q *Queries) GetProductMediaByMurmur(ctx context.Context, arg GetProductMediaByMurmurParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByMurmur, arg.MurmurHash, arg.ProductID)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductMediaByProductID = `-- name: GetProductMediaByProductID :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetProductMediaByProductID(ctx context.Context, productID string) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByProductID, productID)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductPlatformByLazadaID = `-- name: GetProductPlatformByLazadaID :one
SELECT product_id, products_lazada_id FROM products_platform
WHERE products_lazada_id = $1
LIMIT 1
`

func (q *Queries) GetProductPlatformByLazadaID(ctx context.Context, productsLazadaID null.String) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, getProductPlatformByLazadaID, productsLazadaID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductPlatformByProductID = `-- name: GetProductPlatformByProductID :one
SELECT product_id, products_lazada_id FROM products_platform
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetProductPlatformByProductID(ctx context.Context, productID string) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, getProductPlatformByProductID, productID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductsByShopID = `-- name: GetProductsByShopID :many
SELECT products.id, products.name, products.description, products.msku, products.selling_price, products.cost_price, products.shop_id, products.media_id, products.created, products.updated, STRING_AGG(CONCAT(products_media.id, products_media.extension), ',') as media_id_list
FROM products
JOIN products_media ON products_media.product_id = products.id
WHERE shop_id = $1
GROUP BY products.id
`

type GetProductsByShopIDRow struct {
	ID           string         `json:"id"`
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	Msku         null.String    `json:"msku"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       string         `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Created      null.Time      `json:"created"`
	Updated      null.Time      `json:"updated"`
	MediaIDList  []byte         `json:"mediaIDList"`
}

func (q *Queries) GetProductsByShopID(ctx context.Context, shopID string) ([]GetProductsByShopIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByShopIDRow
	for rows.Next() {
		var i GetProductsByShopIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Msku,
			&i.SellingPrice,
			&i.CostPrice,
			&i.ShopID,
			&i.MediaID,
			&i.Created,
			&i.Updated,
			&i.MediaIDList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
 name = coalesce($1, name),
 description = coalesce($2, description),
 msku = coalesce($3, msku),
 selling_price = coalesce($4, selling_price),
 cost_price = coalesce($5, cost_price),
 shop_id = coalesce($6, shop_id),
 media_id = coalesce($7, media_id),
 updated = coalesce($8, updated)
WHERE id = $9
RETURNING id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated
`

type UpdateProductParams struct {
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	Msku         null.String    `json:"msku"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       null.String    `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Updated      null.Time      `json:"updated"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Msku,
		arg.SellingPrice,
		arg.CostPrice,
		arg.ShopID,
		arg.MediaID,
		arg.Updated,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductMedia = `-- name: UpdateProductMedia :one
UPDATE products_media
SET
 product_id = coalesce($1, product_id),
 original_filename = coalesce($2, original_filename),
 murmur_hash = coalesce($3, murmur_hash)
WHERE id = $4
RETURNING id, product_id, original_filename, extension, murmur_hash
`

type UpdateProductMediaParams struct {
	ProductID        null.String `json:"productID"`
	OriginalFilename null.String `json:"originalFilename"`
	MurmurHash       null.Int    `json:"murmurHash"`
	ID               string      `json:"id"`
}

func (q *Queries) UpdateProductMedia(ctx context.Context, arg UpdateProductMediaParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, updateProductMedia,
		arg.ProductID,
		arg.OriginalFilename,
		arg.MurmurHash,
		arg.ID,
	)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}
