// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgtype"
	null "gopkg.in/guregu/null.v4"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, description, msku, selling_price, cost_price, shop_id,
  media_id, updated
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8
)
RETURNING id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated
`

type CreateProductParams struct {
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	Msku         null.String    `json:"msku"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       string         `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Updated      null.Time      `json:"updated"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Msku,
		arg.SellingPrice,
		arg.CostPrice,
		arg.ShopID,
		arg.MediaID,
		arg.Updated,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createProductMedia = `-- name: CreateProductMedia :one
INSERT INTO products_media (
  product_id, original_filename,
  murmur_hash, extension
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, product_id, original_filename, extension, murmur_hash
`

type CreateProductMediaParams struct {
	ProductID        string      `json:"productID"`
	OriginalFilename null.String `json:"originalFilename"`
	MurmurHash       null.Int    `json:"murmurHash"`
	Extension        null.String `json:"extension"`
}

func (q *Queries) CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, createProductMedia,
		arg.ProductID,
		arg.OriginalFilename,
		arg.MurmurHash,
		arg.Extension,
	)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const createProductPlatform = `-- name: CreateProductPlatform :one
INSERT INTO products_platform (
  product_id, products_lazada_id
) VALUES (
  $1, $2
)
RETURNING product_id, products_lazada_id
`

type CreateProductPlatformParams struct {
	ProductID        string      `json:"productID"`
	ProductsLazadaID null.String `json:"productsLazadaID"`
}

func (q *Queries) CreateProductPlatform(ctx context.Context, arg CreateProductPlatformParams) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, createProductPlatform, arg.ProductID, arg.ProductsLazadaID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductByProductMSKU = `-- name: GetProductByProductMSKU :one
SELECT id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated FROM products
WHERE msku = $1 AND shop_id = $2
LIMIT 1
`

type GetProductByProductMSKUParams struct {
	Msku   null.String `json:"msku"`
	ShopID string      `json:"shopID"`
}

func (q *Queries) GetProductByProductMSKU(ctx context.Context, arg GetProductByProductMSKUParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByProductMSKU, arg.Msku, arg.ShopID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductDetailsByID = `-- name: GetProductDetailsByID :one
SELECT products.id, products.name, products.description, products.msku, products.selling_price, products.cost_price, products.shop_id, products.media_id, products.created, products.updated,
  STRING_AGG(CONCAT(products_media.id, products_media.extension), ',') as media_id_list,
  products_lazada.lazada_id as lazada_id,
  products_sku_lazada.url as lazada_url,
  products_attribute_lazada.name as lazada_name,
  products_sku_lazada.sku_id as lazada_platform_sku,
  products_sku_lazada.seller_sku as lazada_seller_sku,
  products_lazada.status as lazada_status
FROM products
JOIN products_media ON products_media.product_id = products.id
JOIN products_platform ON products_platform.product_id = products.id
JOIN products_lazada ON products_platform.products_lazada_id = products_lazada.id
JOIN products_sku_lazada ON products_sku_lazada.product_id = products_lazada.id
JOIN products_attribute_lazada ON products_attribute_lazada.product_id = products_lazada.id
WHERE products.id = $1 AND products.shop_id = $2
GROUP BY products.id, products_lazada.id, products_sku_lazada.id, products_attribute_lazada.id
`

type GetProductDetailsByIDParams struct {
	ID     string `json:"id"`
	ShopID string `json:"shopID"`
}

type GetProductDetailsByIDRow struct {
	ID                string         `json:"id"`
	Name              null.String    `json:"name"`
	Description       null.String    `json:"description"`
	Msku              null.String    `json:"msku"`
	SellingPrice      pgtype.Numeric `json:"sellingPrice"`
	CostPrice         pgtype.Numeric `json:"costPrice"`
	ShopID            string         `json:"shopID"`
	MediaID           null.String    `json:"mediaID"`
	Created           null.Time      `json:"created"`
	Updated           null.Time      `json:"updated"`
	MediaIDList       []byte         `json:"mediaIDList"`
	LazadaID          int64          `json:"lazadaID"`
	LazadaUrl         null.String    `json:"lazadaUrl"`
	LazadaName        null.String    `json:"lazadaName"`
	LazadaPlatformSku null.Int       `json:"lazadaPlatformSku"`
	LazadaSellerSku   string         `json:"lazadaSellerSku"`
	LazadaStatus      null.String    `json:"lazadaStatus"`
}

func (q *Queries) GetProductDetailsByID(ctx context.Context, arg GetProductDetailsByIDParams) (GetProductDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductDetailsByID, arg.ID, arg.ShopID)
	var i GetProductDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
		&i.MediaIDList,
		&i.LazadaID,
		&i.LazadaUrl,
		&i.LazadaName,
		&i.LazadaPlatformSku,
		&i.LazadaSellerSku,
		&i.LazadaStatus,
	)
	return i, err
}

const getProductMediaByID = `-- name: GetProductMediaByID :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductMediaByID(ctx context.Context, id string) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByID, id)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductMediaByMurmur = `-- name: GetProductMediaByMurmur :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE murmur_hash = $1 AND product_id = $2
LIMIT 1
`

type GetProductMediaByMurmurParams struct {
	MurmurHash null.Int `json:"murmurHash"`
	ProductID  string   `json:"productID"`
}

func (q *Queries) GetProductMediaByMurmur(ctx context.Context, arg GetProductMediaByMurmurParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByMurmur, arg.MurmurHash, arg.ProductID)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductMediaByProductID = `-- name: GetProductMediaByProductID :one
SELECT id, product_id, original_filename, extension, murmur_hash FROM products_media
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetProductMediaByProductID(ctx context.Context, productID string) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, getProductMediaByProductID, productID)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}

const getProductPlatformByLazadaID = `-- name: GetProductPlatformByLazadaID :one
SELECT product_id, products_lazada_id FROM products_platform
WHERE products_lazada_id = $1
LIMIT 1
`

func (q *Queries) GetProductPlatformByLazadaID(ctx context.Context, productsLazadaID null.String) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, getProductPlatformByLazadaID, productsLazadaID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductPlatformByProductID = `-- name: GetProductPlatformByProductID :one
SELECT product_id, products_lazada_id FROM products_platform
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetProductPlatformByProductID(ctx context.Context, productID string) (ProductsPlatform, error) {
	row := q.db.QueryRow(ctx, getProductPlatformByProductID, productID)
	var i ProductsPlatform
	err := row.Scan(&i.ProductID, &i.ProductsLazadaID)
	return i, err
}

const getProductsByNameOrSKU = `-- name: GetProductsByNameOrSKU :many
SELECT
  c.count,
  COALESCE(p.id, ''), p.name, p.description, p.msku, p.selling_price, p.cost_price,
  COALESCE(p.shop_id, ''), p.media_id, p.created, p.updated, media_id_list,
  COALESCE(p.lazada_id, 0), lazada_url, lazada_name, lazada_platform_sku,
  COALESCE(lazada_seller_sku, ''), p.lazada_status
FROM
(
  SELECT COUNT(*) AS COUNT
  FROM products
  WHERE products.shop_id = $1 AND (products.name ILIKE $2 OR products.msku ILIKE $3)
) as c
LEFT JOIN (
  SELECT products.id, products.name, products.description, products.msku, products.selling_price, products.cost_price, products.shop_id, products.media_id, products.created, products.updated,
    STRING_AGG(CONCAT(products_media.id, products_media.extension), ',') as media_id_list,
    products_lazada.lazada_id as lazada_id,
    products_sku_lazada.url as lazada_url,
    products_attribute_lazada.name as lazada_name,
    products_sku_lazada.sku_id as lazada_platform_sku,
    products_sku_lazada.seller_sku as lazada_seller_sku,
    products_lazada.status as lazada_status
  FROM products
  JOIN products_media ON products_media.product_id = products.id
  JOIN products_platform ON products_platform.product_id = products.id
  JOIN products_lazada ON products_platform.products_lazada_id = products_lazada.id
  JOIN products_sku_lazada ON products_sku_lazada.product_id = products_lazada.id
  JOIN products_attribute_lazada ON products_attribute_lazada.product_id = products_lazada.id
  WHERE products.shop_id = $1 AND (products.name ILIKE $2 OR products.msku ILIKE $3)
  GROUP BY products.id, products_lazada.id, products_sku_lazada.id, products_attribute_lazada.id
  ORDER BY UPPER(products.name) COLLATE "vi-VN-x-icu"
  LIMIT $4 OFFSET $5
) as p
ON true
`

type GetProductsByNameOrSKUParams struct {
	ShopID string      `json:"shopID"`
	Name   null.String `json:"name"`
	Msku   null.String `json:"msku"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetProductsByNameOrSKURow struct {
	Count             int64          `json:"count"`
	ID                string         `json:"id"`
	Name              null.String    `json:"name"`
	Description       null.String    `json:"description"`
	Msku              null.String    `json:"msku"`
	SellingPrice      pgtype.Numeric `json:"sellingPrice"`
	CostPrice         pgtype.Numeric `json:"costPrice"`
	ShopID            string         `json:"shopID"`
	MediaID           null.String    `json:"mediaID"`
	Created           null.Time      `json:"created"`
	Updated           null.Time      `json:"updated"`
	MediaIDList       []byte         `json:"mediaIDList"`
	LazadaID          int64          `json:"lazadaID"`
	LazadaUrl         null.String    `json:"lazadaUrl"`
	LazadaName        null.String    `json:"lazadaName"`
	LazadaPlatformSku null.Int       `json:"lazadaPlatformSku"`
	LazadaSellerSku   string         `json:"lazadaSellerSku"`
	LazadaStatus      null.String    `json:"lazadaStatus"`
}

func (q *Queries) GetProductsByNameOrSKU(ctx context.Context, arg GetProductsByNameOrSKUParams) ([]GetProductsByNameOrSKURow, error) {
	rows, err := q.db.Query(ctx, getProductsByNameOrSKU,
		arg.ShopID,
		arg.Name,
		arg.Msku,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByNameOrSKURow
	for rows.Next() {
		var i GetProductsByNameOrSKURow
		if err := rows.Scan(
			&i.Count,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Msku,
			&i.SellingPrice,
			&i.CostPrice,
			&i.ShopID,
			&i.MediaID,
			&i.Created,
			&i.Updated,
			&i.MediaIDList,
			&i.LazadaID,
			&i.LazadaUrl,
			&i.LazadaName,
			&i.LazadaPlatformSku,
			&i.LazadaSellerSku,
			&i.LazadaStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByShopID = `-- name: GetProductsByShopID :many
SELECT
  c.count,
  COALESCE(p.id, ''), p.name, p.description, p.msku, p.selling_price, p.cost_price,
  COALESCE(p.shop_id, ''), p.media_id, p.created, p.updated, media_id_list,
  COALESCE(p.lazada_id, 0), lazada_url, lazada_name, lazada_platform_sku,
  COALESCE(lazada_seller_sku, ''), p.lazada_status
FROM
(
  SELECT COUNT(*) AS COUNT
  FROM products
  WHERE products.shop_id = $1
) as c
LEFT JOIN (
  SELECT products.id, products.name, products.description, products.msku, products.selling_price, products.cost_price, products.shop_id, products.media_id, products.created, products.updated,
    STRING_AGG(CONCAT(products_media.id, products_media.extension), ',') as media_id_list,
    products_lazada.lazada_id as lazada_id,
    products_sku_lazada.url as lazada_url,
    products_attribute_lazada.name as lazada_name,
    products_sku_lazada.sku_id as lazada_platform_sku,
    products_sku_lazada.seller_sku as lazada_seller_sku,
    products_lazada.status as lazada_status
  FROM products
  JOIN products_media ON products_media.product_id = products.id
  JOIN products_platform ON products_platform.product_id = products.id
  JOIN products_lazada ON products_platform.products_lazada_id = products_lazada.id
  JOIN products_sku_lazada ON products_sku_lazada.product_id = products_lazada.id
  JOIN products_attribute_lazada ON products_attribute_lazada.product_id = products_lazada.id
  WHERE products.shop_id = $1
  GROUP BY products.id, products_lazada.id, products_sku_lazada.id, products_attribute_lazada.id
  ORDER BY UPPER(products.name) COLLATE "vi-VN-x-icu"
  LIMIT $2 OFFSET $3
) as p
ON true
`

type GetProductsByShopIDParams struct {
	ShopID string `json:"shopID"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetProductsByShopIDRow struct {
	Count             int64          `json:"count"`
	ID                string         `json:"id"`
	Name              null.String    `json:"name"`
	Description       null.String    `json:"description"`
	Msku              null.String    `json:"msku"`
	SellingPrice      pgtype.Numeric `json:"sellingPrice"`
	CostPrice         pgtype.Numeric `json:"costPrice"`
	ShopID            string         `json:"shopID"`
	MediaID           null.String    `json:"mediaID"`
	Created           null.Time      `json:"created"`
	Updated           null.Time      `json:"updated"`
	MediaIDList       []byte         `json:"mediaIDList"`
	LazadaID          int64          `json:"lazadaID"`
	LazadaUrl         null.String    `json:"lazadaUrl"`
	LazadaName        null.String    `json:"lazadaName"`
	LazadaPlatformSku null.Int       `json:"lazadaPlatformSku"`
	LazadaSellerSku   string         `json:"lazadaSellerSku"`
	LazadaStatus      null.String    `json:"lazadaStatus"`
}

func (q *Queries) GetProductsByShopID(ctx context.Context, arg GetProductsByShopIDParams) ([]GetProductsByShopIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByShopID, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByShopIDRow
	for rows.Next() {
		var i GetProductsByShopIDRow
		if err := rows.Scan(
			&i.Count,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Msku,
			&i.SellingPrice,
			&i.CostPrice,
			&i.ShopID,
			&i.MediaID,
			&i.Created,
			&i.Updated,
			&i.MediaIDList,
			&i.LazadaID,
			&i.LazadaUrl,
			&i.LazadaName,
			&i.LazadaPlatformSku,
			&i.LazadaSellerSku,
			&i.LazadaStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
 name = coalesce($1, name),
 description = coalesce($2, description),
 selling_price = coalesce($3, selling_price),
 cost_price = coalesce($4, cost_price),
 shop_id = coalesce($5, shop_id),
 media_id = coalesce($6, media_id),
 updated = coalesce($7, updated)
WHERE id = $8
RETURNING id, name, description, msku, selling_price, cost_price, shop_id, media_id, created, updated
`

type UpdateProductParams struct {
	Name         null.String    `json:"name"`
	Description  null.String    `json:"description"`
	SellingPrice pgtype.Numeric `json:"sellingPrice"`
	CostPrice    pgtype.Numeric `json:"costPrice"`
	ShopID       null.String    `json:"shopID"`
	MediaID      null.String    `json:"mediaID"`
	Updated      null.Time      `json:"updated"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.SellingPrice,
		arg.CostPrice,
		arg.ShopID,
		arg.MediaID,
		arg.Updated,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Msku,
		&i.SellingPrice,
		&i.CostPrice,
		&i.ShopID,
		&i.MediaID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductMedia = `-- name: UpdateProductMedia :one
UPDATE products_media
SET
 product_id = coalesce($1, product_id),
 original_filename = coalesce($2, original_filename),
 murmur_hash = coalesce($3, murmur_hash)
WHERE id = $4
RETURNING id, product_id, original_filename, extension, murmur_hash
`

type UpdateProductMediaParams struct {
	ProductID        null.String `json:"productID"`
	OriginalFilename null.String `json:"originalFilename"`
	MurmurHash       null.Int    `json:"murmurHash"`
	ID               string      `json:"id"`
}

func (q *Queries) UpdateProductMedia(ctx context.Context, arg UpdateProductMediaParams) (ProductsMedia, error) {
	row := q.db.QueryRow(ctx, updateProductMedia,
		arg.ProductID,
		arg.OriginalFilename,
		arg.MurmurHash,
		arg.ID,
	)
	var i ProductsMedia
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OriginalFilename,
		&i.Extension,
		&i.MurmurHash,
	)
	return i, err
}
