// Code generated by sqlc. DO NOT EDIT.
// source: shop.sql

package sqlc

import (
	"context"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (
  shop_name
) VALUES (
  $1
)
RETURNING id, user_id, shop_name, created, last_update
`

func (q *Queries) CreateShop(ctx context.Context, shopName string) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop, shopName)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Created,
		&i.LastUpdate,
	)
	return i, err
}
