CREATE TABLE IF NOT EXISTS users(
  id CHAR(26) DEFAULT ulid_create() NOT NULL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL
);
