BEGIN;
CREATE TABLE IF NOT EXISTS users(
  id CHAR(26) DEFAULT ulid_to_string(ulid_generate()) NOT NULL PRIMARY KEY,
  password VARCHAR(128) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL,
  created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
