version: 1
packages:
  - path: "./.."
    name: "sqlc"
    engine: "postgresql"
    schema: "./../../migrations"
    queries: "./../queries"
    emit_json_tags: true
    json_tags_case_style: "camel"
    sql_package: "pgx/v4"
