version: 1
packages:
  - path: "./.."
    name: "sqlc"
    engine: "postgresql"
    schema: "./../../migrations"
    queries: "./../queries"
    emit_json_tags: true
    json_tags_case_style: "camel"
    sql_package: "pgx/v4"
overrides:
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: String
    db_type: "pg_catalog.varchar"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: String
    db_type: "pg_catalog.bpchar"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: String
    db_type: "text"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: String
    db_type: "string"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: Time
    db_type: "pg_catalog.timestamptz"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: Int
    db_type: "pg_catalog.int8"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: Int
    db_type: "pg_catalog.int4"
    nullable: true
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: Int
    db_type: "bigserial"
    nullable: true
